export const environment = {
  production: true,
  name: 'Medicinedipo',
  domain: 'medicinedipo.com',
  apiBaseLink: 'https://api.healthynikah.com',
  ftpBaseLink: 'https://api.healthynikah.com',
  appBaseUrl: '/',
  userBaseUrl: 'home',
  deliverymanBaseUrl: 'dashboard',
  userProfileUrl: '/my-profile',
  userLoginUrl: '/authintication',
  deliverymanLoginUrl: '/',
  adminLoginUrl: 'login',
  adminBaseUrl: '/',
  storageSecret: 'SOFT_2021_IT_1998',
  adminTokenSecret: 'SOFT_ADMIN_1995_&&_SOJOL_dEv',
  userTokenSecret: 'SOFT_ADMIN_1996_&&_SOBUR_dEv',
  apiTokenSecret: 'SOFT_API_1998_&&_SAZIB_dEv',
  stripePublishableKey: 'pk_test_51LXis9EdSP1amkCQEkJLm7cT9vKbBClSDwBP1WFCOeMf4DDpkNjrl7GuhEi3EfAnLgpefYLRz7zZcdnUQ8aPjjuC00VfZ5OBsk',
  stripeSecretKey: 'sk_test_51LXis9EdSP1amkCQPqmmUdiVj9DjxwWUnzI4l0Ju3yQj3jrqCxkJbu0ZguAPSV0ACpSxGg45PzIecfbRKvmVDmTb00KqwU8Tsy',
  VERSION: 2,
  AndroidVersion: '1.2',
};
